### ISSUE TITLE
შეკითხვა N26-ში

### ISSUE THREAD

**Issue by getsadzeg** [CSenshi/FreeUni-Programming-Methodology-2020#1]
https://github.com/CSenshi/FreeUni-Programming-Methodology-2020/blob/45f0fa01cd06a7322b0829eb051094b0dee85d02/s09/Ex26.java#L33

თუ a ყოველთვის მეტია ან ტოლია b-სი, b-მდე არ უნდა გვქონდეს ციკლი? უსგ ხომ ვერ იქნება უფრო მეტი ვიდრე ერთ-ერთი რიცხვი.

მასე უფრო ცხადი იქნება მგონი კოდი.

**Comment by CSenshi** [comment]
* _"უსგ ხომ ვერ იქნება უფრო მეტი ვიდრე ერთ-ერთი რიცხვი"_ ამაში გეთანხმები, ანუ:
   ```
    თუ b <= a:
        GCD(a, b) <= b <= a
   ```
* _"თუ a ყოველთვის მეტია ან ტოლია b-სი, b-მდე არ უნდა გვქონდეს ციკლი"_ ამ ნაწილში თუ გულისხმობ რომ ციკლი დავიწყოთ b-დან და არა a-დან მაშინ, სწორია, თუ გულისხმობ რომ დავიწყოთ a-დან და ჩავუყვეთ b-მდე ეს, მაშინ არა.

    * სწორია:
        ```java
        ...
        for (int i = b; i >= 1; i--) { 
        ...
        ```

    * არასწორია:
        ```java
        ...
        for (int i = a; i >= b; i--) { 
        ...
        ```

**Comment by getsadzeg** [comment]
კი რაც "სწორია" სექციაში გიწერია მაგას ვგულისხმობდი.
