### ISSUE TITLE
შეცდომა N32-ში

### ISSUE THREAD

**Issue by getsadzeg** [CSenshi/FreeUni-Programming-Methodology-2020#2]
https://github.com/CSenshi/FreeUni-Programming-Methodology-2020/blob/45f0fa01cd06a7322b0829eb051094b0dee85d02/s10/Ex32.java#L10

საბა, ეს კონსტანტა მილიონი არ უნდა იყოს? თორემ მასე 1000-მდე ბეჭდავს მარტივ რიცხვებს.

**Comment by CSenshi** [comment]
კი, პირობაში 1'000'000 წერია და აქაც მაგდენი უნდა იყოს და არა 1'000. მილიონის არდაწერა გადავწყვიტე იმიტომ, რომ ზედმეტად ბევრ დროს/რესურსს მოითხოვს რიცხვის მარტივობის შემოწმება ჩვენი ალგორითმით (რიცხვი რაც უფრო იზრდება მით უფრო მეტი ოპერაცია სჭირდება) და მე პირადად შუა გამოთვლისას პროგრამა დამექრაშა. ამიტომ ვიფიქრე არავინ არ მიწყენდა თუ რიცხვს შევამცირებდი.

**Comment by getsadzeg** [comment]
უი. ოკეი მაშინ. მეგონა typo იყო :DD
