### ISSUE TITLE
შეცდომა ერთ-ერთ ამოხსნაში

### ISSUE THREAD

**Issue by NikolozCh** [CSenshi/FreeUni-Programming-Methodology-2020#3]
სალამი,

ვფიქრობ, შეცდომა აღმოვაჩინე ამოხსნის ტესტ-ქეისში.

ამოცანა: 2019 წლის ფინალური, მე-2 ვარიანი, ამოცანა N: 2

https://github.com/CSenshi/FreeUni-Programming-Methodology-2020/blob/748cf20d3f825a233dbb2ff5bd0900e853e19913/exams/f2019_v2/F2019_V2_Ex02.java#L28

28-ე ხაზზე `int realResult = 4;` ის მაგივრად უნდა იყოს `int realResult = 3;`, ვინაიდან რობოტი 3 ვაშლს მიირთმევს კონკრეტულ მაპზე.

ამ კოდიდან გამომდინარე:
```java
String[] insturctions = new String[] { "move", // 0x0 -> 0x1
  "left", "left", "left", // turn right
  "move", // 0x1 -> 1x1 (Eat Apple)
  "move", // 1x1 -> 1x2 (Eat Apple)
  "move", // 1x2 -> X (Stone!)
  "left", "left", "left", // turn right
  "move", // 1x2 -> 0x2
  "left", "left", "left", // turn right
  "move" // 0x2 -> 0x1 (Eat Apple)
};
```

Cheers.

**Comment by CSenshi** [comment]
4-ჯერ შეჭამს.

3-ს შეჭამს მოძრაობით, მაგრამ გასათვალისწინებელი გვაქვს ისიც, რომ საწყის წერტილზე (0x0) დევს ვაშლი, რომელიც ასევე უნდა შეჭამოს, ამიტომაც 4 უნდა იყოს.

სამწუხაროდ კომენტარებში არ მაქვს მიწერილი და ეგ კი გამომრჩა

**Comment by NikolozCh** [comment]
ჰმმმ.. კარგი 😃

ვხურავ.
